### ISSUE TITLE
Synthetic dataset

### ISSUE THREAD

**Issue by slavaheroes** [mobaidoctor/med-ddpm#13]
Thank you for your work! 

I want to utilize your synthetic dataset (https://ieee-dataport.org/documents/synthetic-whole-head-mri-brain-tumor-segmentation-dataset) but unfortunately, I don't have an IEEE subscription which is a bit costly. 

Is sharing it via Google Drive or any other free platform possible?

Thank you.

**Comment by mobaidoctor** [comment]
Yes, we have made our synthetic datasets available for the Intracranial Tumor Segmentation (ICTS) Challenge. You can find and download the training sets directly from the challenge's homepage. For more details, please visit: https://github.com/mobaidoctor/med-ddpm/discussions/7.
