### ISSUE TITLE
Error whith inference from newly trained model

### ISSUE THREAD

**Issue by LRpz** [mobaidoctor/med-ddpm#16]
Hi, 

Thank you very much for your codebase, it is very clean! 
I could successfully train your model on the whole_head dataset that your provided using your 'train.py' script. 

Although, running inference ('sample.py') using your pretrained model 'model_128.pt' does work, I do get an error when trying to load a model that resulted from my training. 

```
model = create_model(input_size, num_channels, num_res_blocks, in_channels=in_channels, out_channels=out_channels).cuda()
diffusion = GaussianDiffusion(
    model,
    image_size = input_size,
    depth_size = depth_size,
    timesteps = 250,   # number of steps
    loss_type = 'L1', 
    with_condition=True,
).cuda()

diffusion.load_state_dict(torch.load(weightfile)['ema'])
print("Model Loaded!")
```

returns:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> [c:\Users\rappez\Documents\git_codebase\med-ddpm\sample.py](file:///C:/Users/rappez/Documents/git_codebase/med-ddpm/sample.py) in line 11
>       [77](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=76) model = create_model(input_size, num_channels, num_res_blocks, in_channels=in_channels, out_channels=out_channels).cuda()
>       [78](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=77) diffusion = GaussianDiffusion(
>       [79](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=78)     model,
>       [80](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=79)     image_size = input_size,
>    (...)
>       [84](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=83)     with_condition=True,
>       [85](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=84) ).cuda()
> ---> [87](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=86) diffusion.load_state_dict(torch.load(weightfile)['ema'])
>      [88](file:///c%3A/Users/rappez/Documents/git_codebase/med-ddpm/sample.py?line=87) print("Model Loaded!")
> 
> File [c:\Users\rappez\Anaconda3\envs\torch_apex\lib\site-packages\torch\nn\modules\module.py:2153](file:///C:/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py:2153), in Module.load_state_dict(self, state_dict, strict, assign)
>    [2148](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2147)         error_msgs.insert(
>    [2149](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2148)             0, 'Missing key(s) in state_dict: {}. '.format(
>    [2150](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2149)                 ', '.join(f'"{k}"' for k in missing_keys)))
>    [2152](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2151) if len(error_msgs) > 0:
> -> [2153](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2152)     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
>    [2154](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2153)                        self.__class__.__name__, "\n\t".join(error_msgs)))
>    [2155](file:///c%3A/Users/rappez/Anaconda3/envs/torch_apex/lib/site-packages/torch/nn/modules/module.py?line=2154) return _IncompatibleKeys(missing_keys, unexpected_keys)
> 
> RuntimeError: Error(s) in loading state_dict for GaussianDiffusion:
> 	size mismatch for denoise_fn.input_blocks.0.0.weight: copying a param with shape torch.Size([64, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 3]).

**Comment by mobaidoctor** [comment]
Hi, the error message you're encountering indicates a mismatch in the shape of model parameters. The shape of the weight tensor in the checkpoint you are trying to load is torch.Size([64, 1, 3, 3, 3]), whereas the shape expected by your current model definition in your sample.py is torch.Size([64, 3, 3, 3, 3]). Please update your inference script 'sample.py' to use the same input channel configuration as your training script.
