### ISSUE TITLE
class conditioning

### ISSUE THREAD

**Issue by asmaseraj** [mobaidoctor/med-ddpm#17]
Hi. Hope you're doing well.
I've seen that in the code you've mentioned that the model could be class-conditioned. I have a dataset that contains three subfolders (so I have three classes), each with its distinct feature. Can I utilize Med-DDPM to train a class-conditioned model? How can I achieve this and what changes should I implement on the model? I would appreciate it if you could provide some guidance for me.
Thank you so much.

**Comment by mobaidoctor** [comment]
Thank you for contacting us. Have you had a chance to review our manuscript? Our work focuses on semantic image synthesis, an area previously underexplored in the literature. The current version of our code is designed solely for this purpose and does not include class conditioning. The term "class" in our manuscript refers to class labels for segmentation masks. Specifically, we explain that "The dataset's segmentation mask includes three class labels: 0 for the background, 1 for the head area, and 2 for the tumor area."
If you are interested in using our code for class-conditioned synthesis, where training images are organized into classes, it would require modifications. Our approach is aimed at pixel-to-pixel translation, specifically from mask to image synthesis, without using a latent vector.
For class-conditioned synthesis, you can find diffusion-based models easily (e.g., https://arxiv.org/pdf/2112.10752.pdf ), as this topic is well-covered in research literature. We hope this helps, and wish you the best in your research.

**Comment by asmaseraj** [comment]
Thank you so much for your guidance, I deeply appreciate your quick response.
I am excited to read your future research papers.
