### ISSUE TITLE
Color Consistency during the training when the model is trained on another new medical dataset. 

### ISSUE THREAD

**Issue by junzhin** [mobaidoctor/med-ddpm#18]
Hello,

I've encountered an issue while training a model on a new CT scan dataset. It seems that the output images aren't displaying the correct colours. The dataset I'm using is fairly small, comprising just around 50 images, each with a resolution 512x512x512. I've trained the model for 1800 epochs and have implemented random cropping as a form of data augmentation.

Could anyone provide insight into why this might be occurring? I'm looking for guidance on how to troubleshoot this problem. Do I need to increase the number of training or increase the size of the dataset?  

Thank you very much!

**Comment by mobaidoctor** [comment]
Hi, thank you for reaching out. Could you clarify what you mean by 'correct colors'? Are you referring to the CT number? Please provide more details about your issue. A screenshot would greatly help in understanding your issue more quickly.

**Comment by mobaidoctor** [comment]
@junzhin If your issue is resolved and you have no further questions, I will proceed to close this issue.
