### ISSUE TITLE
Python version to run the code

### ISSUE THREAD

**Issue by kitofito** [mobaidoctor/med-ddpm#3]
Hi, thank you very much for sharing your work. I am interested in running your code without modifying it, I have managed to install the requirements but I have other errors and I don't know if they are due to the Python version. What version of Python did you use to run the code?

Thank you.

**Comment by z0l00** [comment]
Hi, thanks for reaching out! We utilized Python 3.8.10 for this project. Please don't hesitate to ask if you need any more clarifications or have further questions. We’re always here to help 🤗 and value your feedback 📢 to enhance our work.

**Comment by mobaidoctor** [comment]
Hi, thanks for reaching out! We utilize Python 3.8.10 for this project. Please don't hesitate to ask if you need any more clarifications or have further questions. We're always here to help and value feedback to enhance our work.
