### ISSUE TITLE
About generation data with sample_brats.py

### ISSUE THREAD

**Issue by supgy** [mobaidoctor/med-ddpm#31]
Hello dear author, I download BraTS2021 and then execute preprocess_brats_data.py and put the results into 'dataset/brats2021'. Then I try to generate new data using sample_brats.py, but I get the following result,I dont know where is the preblem? Your data in github can yield accurate results
![image](https://github.com/user-attachments/assets/7e2731a2-c92f-456e-8dd9-dccf30d5cb73)

**Comment by mobaidoctor** [comment]
@supgy Hi, Thank you for your interest in our work. Could you please send us the exact input mask image you used with the inference script? (to email: mobaidoctor@gmail.com). Please ensure that your mask image has been processed using the preprocess_seg function from the preprocess_brats_data.py file in our repository before you input it into the sampling script. Thank you.

**Comment by supgy** [comment]
I have sent it to your email. Thank you for taking the time to answer amidst your busy schedule.♥

**Comment by mobaidoctor** [comment]
https://github.com/mobaidoctor/med-ddpm/issues/28#issuecomment-2230830747
