### ISSUE TITLE
Release of the four modalities weights and code

### ISSUE THREAD

**Issue by Lucas-rbnt** [mobaidoctor/med-ddpm#4]
Hello,

First of all I'd like to thank you for your superb paper and the associated code. As part of my work I had tried to do something quite similar on the 4 MRI modalities but was limited from a hardware point of view. On this subject I'd like to know if you have any hindsight on when you'll be able to release the weight of this model. Thanks again for your work,

Have a nice day!

**Comment by mobaidoctor** [comment]
Thank you, Lucas, for your interest in our work. We apologize for the delay in our response as we've been deeply engaged in intensive research tasks. We're excited to inform you that we have now released the weights and corresponding code sections for our 4 modalities generation model. To train all four modalities, please note that each modality image should have dimensions of 192x192x144, requiring at least one NVIDIA A100 80GB GPU. Our model was trained on a single A100 GPU. For inference, you will need a GPU with a minimum of 18GB, such as an RTX3090 (24GB) or higher, as the inference process requires 16.68 GB.
